#ifndef BONGO_CAT_MODEL_COVER_PATHS_H
#define BONGO_CAT_MODEL_COVER_PATHS_H

#define BONGO_CAT_MODEL_COVER_RESOURCES "resources"
#define BONGO_CAT_MODEL_COVER_FILE BONGO_CAT_MODEL_COVER_RESOURCES "/cover.png"
#define BONGO_CAT_MODEL_COVER_FALLBACK_NAME ".bongo-cat-cover-fallback"
#define BONGO_CAT_MODEL_COVER_GENERATED_NAME ".bongo-cat-cover-generated"
#define BONGO_CAT_MODEL_COVER_FALLBACK_MARKER \
    BONGO_CAT_MODEL_COVER_RESOURCES "/" BONGO_CAT_MODEL_COVER_FALLBACK_NAME
#define BONGO_CAT_MODEL_COVER_GENERATED_MARKER \
    BONGO_CAT_MODEL_COVER_RESOURCES "/" BONGO_CAT_MODEL_COVER_GENERATED_NAME

#endif
