#ifndef BONGO_CAT_MODEL_COVER_PATHS_H
#define BONGO_CAT_MODEL_COVER_PATHS_H

#define BONGO_CAT_MODEL_COVER_RESOURCES "resources"
#define BONGO_CAT_MODEL_COVER_FILE BONGO_CAT_MODEL_COVER_RESOURCES "/cover.png"

#endif
