blank_issues_enabled: true
contact_links:
  - name: 💬 Questions & Discussions 💬
    url: https://github.com/vladelaina/BongoCat/discussions
    about: "🤝 Have a question or want to chat? Join our friendly community discussions!"
